import {PRODUCTS,SERVICES,LOGISTICS} from '../../data/catalog.js';
import {shell,bind,icon} from '../../app/ui.js';
const DATA={
 'besi-baja':{title:'Besi & Baja',eyebrow:'MATERIAL • STRUKTUR',intro:'Material struktur untuk pondasi, kolom, balok, rangka, dan kebutuhan konstruksi lainnya.',why:'Pilih berdasarkan diameter, panjang, jenis baja, kebutuhan proyek, stok dan jadwal delivery.',items:['mat-001','mat-002'],chips:['Besi Beton','Besi Ulir','Wiremesh','Baja Ringan']},
 'semen-beton':{title:'Semen & Beton',eyebrow:'MATERIAL • KONSTRUKSI',intro:'Semen, mortar dan kebutuhan beton untuk pekerjaan struktur, pasangan, lantai, dan finishing konstruksi.',why:'Perhatikan tipe produk, berat per kemasan, kebutuhan volume dan waktu pemakaian di lokasi.',items:['mat-003'],chips:['Semen Portland','Mortar','Beton']},
 'pasir-batu':{title:'Pasir & Batu',eyebrow:'MATERIAL • AGREGAT',intro:'Pasir, batu split dan agregat untuk pondasi, beton, pasangan, drainase, dan pekerjaan luar ruang.',why:'Volume, ukuran agregat, akses kendaraan dan jadwal bongkar sangat menentukan biaya pengadaan.',items:['mat-007'],chips:['Pasir','Batu Split','Batu Kali']},
 'kayu-multiplek':{title:'Kayu & Multiplek',eyebrow:'MATERIAL • KAYU',intro:'Kayu, multiplek dan material lembaran untuk konstruksi, bekisting, interior, dan pekerjaan custom.',why:'Bandingkan ketebalan, ukuran lembar, kualitas permukaan dan ketersediaan potongan.',items:['mat-004'],chips:['Multiplek','Kayu','Papan']},
 'cat-pelapis':{title:'Cat & Finishing',eyebrow:'MATERIAL • FINISHING',intro:'Cat interior, exterior dan material finishing untuk melindungi sekaligus menyelesaikan tampilan bangunan.',why:'Sesuaikan jenis cat dengan permukaan, area penggunaan, coverage dan jumlah lapisan.',items:['mat-005'],chips:['Cat Interior','Cat Exterior','Pelapis']},
 'pipa-plumbing':{title:'Plumbing',eyebrow:'MATERIAL • PLUMBING',intro:'Pipa, fitting, valve dan kebutuhan instalasi air untuk rumah, villa, gedung dan proyek komersial.',why:'Pastikan diameter, material pipa, tekanan kerja dan kompatibilitas fitting sebelum membeli.',items:['mat-006'],chips:['Pipa PVC','Fitting','Valve']},
 'listrik':{title:'Listrik',eyebrow:'MATERIAL • ELECTRICAL',intro:'Kabel, saklar, panel dan komponen kelistrikan untuk instalasi bangunan dan kebutuhan proyek.',why:'Spesifikasi kabel, kapasitas, standar keselamatan dan kebutuhan daya harus sesuai rancangan instalasi.',items:['mat-002'],chips:['Kabel','Saklar','Panel Listrik']},
 'atap':{title:'Atap',eyebrow:'MATERIAL • ROOFING',intro:'Material atap untuk perlindungan bangunan, renovasi, rumah tinggal dan proyek komersial.',why:'Pertimbangkan jenis material, luas bidang, kemiringan, aksesoris dan metode pemasangan.',items:['mat-008'],chips:['Genteng','Metal','Aksesoris Atap']},
 'tukang-bangunan':{title:'Tukang Bangunan',eyebrow:'JASA • TENAGA PROYEK',intro:'Tenaga tukang untuk pekerjaan pembangunan, perbaikan dan pekerjaan harian di lokasi proyek.',why:'Tentukan jenis pekerjaan, jumlah tenaga, durasi dan lokasi sebelum booking.',items:['svc-001'],chips:['Harian','Borongan','Survey']},
 'plumbing-service':{title:'Jasa Plumbing',eyebrow:'JASA • PLUMBING',intro:'Layanan instalasi, perbaikan dan pemeriksaan plumbing untuk bangunan dan proyek.',why:'Jelaskan titik pekerjaan, jenis masalah dan akses lokasi agar kebutuhan tenaga dapat diperkirakan.',items:['svc-003'],chips:['Perbaikan','Instalasi','Survey']},
 'renovasi':{title:'Renovasi',eyebrow:'JASA • PROJECT',intro:'Bantuan survey dan pekerjaan renovasi untuk rumah, villa, ruang usaha dan bangunan lainnya.',why:'Mulai dari kondisi existing, scope pekerjaan, target waktu dan estimasi kebutuhan material.',items:['svc-004'],chips:['Survey','Renovasi Rumah','Project']},
 'pickup':{title:'Pickup Delivery',eyebrow:'LOGISTICS • LIGHT DELIVERY',intro:'Pilihan pickup untuk kebutuhan material dengan volume ringan hingga menengah.',why:'Sesuaikan kendaraan dengan ukuran barang, lokasi pickup, tujuan, waktu dan akses proyek.',items:['log-001'],chips:['Pickup','Same Day','Scheduled']},
 'l300':{title:'L300 Angkutan Proyek',eyebrow:'LOGISTICS • PROJECT TRANSPORT',intro:'Angkutan L300 untuk material proyek dan pengiriman yang membutuhkan ruang lebih besar.',why:'Periksa dimensi muatan, berat, rute, waktu pickup dan kebutuhan bongkar.',items:['log-002'],chips:['L300','Material','Project Delivery']},
 'truck':{title:'Truck Material',eyebrow:'LOGISTICS • HEAVY DELIVERY',intro:'Pilihan truck untuk material ber-volume besar dan kebutuhan pengiriman proyek.',why:'Pilih berdasarkan volume, berat, akses jalan, titik bongkar dan jadwal proyek.',items:['log-003'],chips:['Truck','Volume Besar','Project']},
 'bongkar-muat':{title:'Bongkar Muat',eyebrow:'LOGISTICS • SITE SUPPORT',intro:'Tenaga bongkar muat untuk membantu material tiba, diturunkan dan ditangani di lokasi proyek.',why:'Tentukan jenis material, volume, akses lokasi dan waktu pekerjaan sebelum memesan tenaga.',items:['log-004'],chips:['Tenaga','Bongkar','Site Support']}
};
const ALL=[...PRODUCTS,...SERVICES,...LOGISTICS];
const find=id=>ALL.find(x=>x.id===id);
function card(x){return '<article class="market-card"><a href="#/detail/'+x.id+'" class="market-image"><img src="'+x.image+'" alt="'+x.title+'" loading="lazy"><button type="button" class="save" data-wish="'+x.id+'" aria-label="Simpan ke wishlist">'+icon.heart+'</button></a><div class="market-body"><small>'+x.type.toUpperCase()+'</small><a href="#/detail/'+x.id+'" class="market-title">'+x.title+'</a><div class="rating">★ '+(x.rating||4.8)+' <span>(demo)</span></div><strong>Rp '+new Intl.NumberFormat('id-ID').format(x.price)+'</strong><span>/ '+(x.unit||'item')+'</span><div class="supplier-count">'+(x.type==='material'?'Supplier terverifikasi · stok & delivery di detail':'Bisa dipesan')+'</div><a class="market-card-cta" href="#/detail/'+x.id+'">Lihat detail '+icon.arrow+'</a></div></article>';}
export function categoryPage(slug=''){
 const d=DATA[slug];
 if(!d)return shell('<div class="empty-state large"><h1>Kategori belum tersedia</h1><a class="primary-button" href="#/material">Kembali ke kategori</a></div>','Kategori',{hero:false});
 const items=d.items.map(find).filter(Boolean);
 const topics=d.chips.map((x,i)=>'<a class="category-topic" href="#/search?q='+encodeURIComponent(x)+'"><span>'+['◈','◇','▦','○'][i%4]+'</span>'+x+' '+icon.arrow+'</a>').join('');
 const html='<div class="category-page category-page-'+slug+'"><div class="breadcrumb">Home / '+d.title+'</div><section class="category-intro"><div><span class="eyebrow">PANDUAN KATEGORI</span><h2>Pahami kebutuhan sebelum memilih</h2><p>Pilihan di kategori ini disusun untuk membantu Anda membandingkan spesifikasi, supplier, ketersediaan, dan kebutuhan delivery proyek.</p></div><div class="category-intro-note"><b>Bagaimana memilih?</b><span>'+d.why+'</span></div></section><div class="category-topics">'+topics+'</div><div class="listing-top"><div><h2>Produk & pilihan '+d.title+'</h2><p>Data frontend/demo saat ini. Harga, stok dan supplier akan terhubung ke backend.</p></div><a class="secondary-button" href="#/search?q='+encodeURIComponent(d.title)+'">'+icon.search+' Cari lebih banyak</a></div><div class="category-product-grid">'+items.map(card).join('')+'</div><section class="category-help"><div><span class="eyebrow">NEED HELP?</span><h2>Butuh jumlah atau spesifikasi khusus?</h2><p>Untuk kebutuhan proyek yang tidak tersedia di katalog, gunakan pencarian atau hubungi tim Bali Bagus.</p></div><a class="primary-button" href="#/contact">Hubungi Bali Bagus '+icon.arrow+'</a></section></div>';
 const out=shell(html,d.title,{hero:true,heroLabel:d.eyebrow,heroDescription:d.intro});
 queueMicrotask(()=>bind());
 return out;
}