import {shell} from '../../app/ui.js';
const posts=[
 ['cara-memilih-besi-beton','Material Guide','Cara memilih besi beton yang tepat untuk proyek','https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=85'],
 ['hitung-kebutuhan-semen','Construction','Cara menghitung kebutuhan semen sebelum membeli','https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=85'],
 ['pilih-truck-material','Delivery','Memilih truck sesuai jenis dan volume material','https://images.unsplash.com/photo-1601584115197-04ecc0da31d8?auto=format&fit=crop&w=1200&q=85'],
 ['checklist-renovasi','Project Planning','Checklist kebutuhan material untuk renovasi rumah','https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=85']];
export function blog(slug=''){
 const p=posts.find(x=>x[0]===slug);
 if(p)return shell('<article class="article-page"><div class="article-breadcrumb"><a href="#/blog">Guides</a> / '+p[1]+'</div><div class="article-head"><span class="eyebrow">'+p[1]+'</span><h1>'+p[2]+'</h1><p>Practical guidance from Bali Bagus for materials, procurement and project delivery.</p><small>Updated 2026 · Bali Bagus Editorial</small></div><img class="article-cover" src="'+p[3]+'" alt="'+p[2]+'"><div class="article-layout"><div class="article-body"><p>Keputusan material sebaiknya dimulai dari kebutuhan pekerjaan, spesifikasi, jumlah, ketersediaan dan waktu pengiriman. Gunakan panduan ini sebagai checklist sebelum membeli.</p><h2>Mulai dari kebutuhan proyek</h2><p>Tentukan jenis pekerjaan, ukuran atau spesifikasi, jumlah, lokasi proyek dan kapan material harus tersedia. Catat semuanya dalam satu daftar.</p><h2>Bandingkan supplier, bukan hanya harga</h2><p>Periksa harga, stok, rating supplier, minimum order, waktu persiapan, area layanan dan pilihan delivery. Dengan begitu Anda dapat melihat biaya dan risiko secara lebih menyeluruh.</p><div class="article-callout"><b>Tip proyek</b><span>Simpan material penting ke wishlist dan gunakan cart untuk menggabungkan kebutuhan dari beberapa supplier.</span></div><h2>Siapkan delivery</h2><p>Pastikan alamat, akses kendaraan, ruang bongkar dan waktu penerimaan jelas. Untuk material berat atau banyak, pilih kendaraan berdasarkan volume dan kebutuhan proyek.</p><h2>Checklist sebelum checkout</h2><ul><li>Spesifikasi dan satuan sudah benar.</li><li>Jumlah sesuai kebutuhan pekerjaan.</li><li>Penawaran supplier sudah dibandingkan.</li><li>Alamat dan akses proyek jelas.</li><li>Jadwal delivery sesuai kebutuhan.</li></ul></div><aside class="article-side"><div><b>On this page</b><a href="#article">Project needs</a><a href="#article">Compare suppliers</a><a href="#article">Delivery</a><a href="#article">Checkout checklist</a></div><a class="article-cta" href="#/material"><b>Ready to shop?</b><span>Compare materials →</span></a></aside></div><section class="article-related"><h2>More guides</h2><div class="blog-grid">'+posts.filter(x=>x[0]!==p[0]).slice(0,3).map(x=>'<a class="blog-card" href="#/article/'+x[0]+'"><img src="'+x[3]+'" alt="'+x[2]+'"><div><small>'+x[1]+'</small><h3>'+x[2]+'</h3><span>Read guide →</span></div></a>').join('')+'</div></section></article>','Guide');
 return shell('<div class="blog-page"><div class="blog-hero"><span class="eyebrow">BALI BAGUS GUIDES</span><h1>Ideas, guides & stories for better projects.</h1><p>Material guides, buying tips, project planning and delivery knowledge for Bali construction.</p></div><div class="blog-toolbar"><b>Explore guides</b><nav><a class="active" href="#/blog">All</a><a href="#/blog">Buying Guides</a><a href="#/blog">Material Guides</a><a href="#/blog">Delivery</a><a href="#/blog">Project Planning</a></nav></div><a class="featured-post" href="#/article/'+posts[0][0]+'"><img src="'+posts[0][3]+'" alt="'+posts[0][2]+'"><div><span>'+posts[0][1]+'</span><h2>'+posts[0][2]+'</h2><p>Start with the right material, supplier and delivery plan.</p><small>Read guide →</small></div></a><div class="blog-grid">'+posts.slice(1).map(x=>'<a class="blog-card" href="#/article/'+x[0]+'"><img src="'+x[3]+'" alt="'+x[2]+'" loading="lazy"><div><small>'+x[1]+'</small><h3>'+x[2]+'</h3><p>Practical guidance for your project.</p><span>Read guide →</span></div></a>').join('')+'</div></div>','Project Guides');
}