import {icon,header,footer,nav} from '../../app/ui.js';
import {PRODUCTS} from '../../data/catalog.js';
import {store} from '../../app/store.js';

const categories=[
 ['Besi & Baja','besi-baja','https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=82'],
 ['Semen & Beton','semen-beton','https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&q=82'],
 ['Pasir & Batu','pasir-batu','https://images.unsplash.com/photo-1590579491624-f98f36d4c763?auto=format&fit=crop&w=800&q=82'],
 ['Kayu & Multiplek','kayu-multiplek','https://images.unsplash.com/photo-1531835551805-16d864c8d1c6?auto=format&fit=crop&w=800&q=82'],
 ['Cat & Finishing','cat-pelapis','https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=800&q=82'],
 ['Listrik','listrik','https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=800&q=82'],
 ['Plumbing','pipa-plumbing','https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=800&q=82'],
 ['Atap','atap','https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=82']
];
const areas=[
 ['Denpasar','Urban projects','https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=82'],
 ['Badung','Villa & hospitality','https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=82'],
 ['Gianyar','Renovation','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=82'],
 ['Ubud','Villa projects','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=82']
];
const guides=[
 ['cara-memilih-besi-beton','Material Guide','Cara memilih besi beton yang tepat untuk proyek','https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1000&q=82'],
 ['hitung-kebutuhan-semen','Construction','Cara menghitung kebutuhan semen sebelum membeli','https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1000&q=82'],
 ['pilih-truck-material','Delivery','Memilih truck sesuai jenis dan volume material','https://images.unsplash.com/photo-1601584115197-04ecc0da31d8?auto=format&fit=crop&w=1000&q=82'],
 ['checklist-renovasi','Project Planning','Checklist kebutuhan material untuk renovasi','https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1000&q=82']
];

function deal(p){return `<a href="#/detail/${p.id}" class="deal-card"><div class="deal-image"><img src="${p.image}" alt="${p.title}" loading="lazy"><span>DEMO DEAL</span><button type="button" class="deal-heart" data-wish="${p.id}">${icon.heart}</button></div><div class="deal-body"><small>Construction material</small><h3>${p.title}</h3><div class="deal-rating">★ ${p.rating||4.8} <span>(demo)</span></div><strong>Rp ${new Intl.NumberFormat('id-ID').format(p.price)}</strong><p>3 supplier · Delivery tersedia</p></div></a>`}
export function home(){
 const slides=[
  ['https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=2200&q=88','BALI BAGUS LOAD & DELIVERY','Everything your project needs.','In one place.','Temukan material, bandingkan supplier, atur delivery, dan kelola kebutuhan proyek dari satu marketplace.','Cari besi beton, semen, pipa...'],
  ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=2200&q=88','COMPARE BEFORE YOU BUY','More choices.','Better project decisions.','Bandingkan harga, stok, rating supplier dan ketersediaan sebelum membeli.','Cari material atau brand...'],
  ['https://images.unsplash.com/photo-1601584115197-04ecc0da31d8?auto=format&fit=crop&w=2200&q=88','ONE MARKETPLACE · ONE WORKFLOW','From supplier','to project site.','Gabungkan kebutuhan dari beberapa supplier dan biarkan Bali Bagus mengoordinasikan pickup, loading dan delivery.','Cari delivery atau material...']
 ];
 return `${header()}<section class="klook-hero hero-carousel"><div class="hero-slides">${slides.map((s,i)=>`<article class="hero-slide ${i===0?'is-active':''}" style="--hero-image:url('${s[0]}')"><div class="klook-hero-overlay"></div><div class="klook-hero-inner"><span class="hero-label">${s[1]}</span><h1>${s[2]}<br><em>${s[3]}</em></h1><p>${s[4]}</p><form class="hero-search klook-search hero-slide-search"><span>${icon.search}</span><input placeholder="${s[5]}" aria-label="Cari kebutuhan proyek"><button>Cari</button></form><div class="popular-search"><b>Sering dicari:</b><a href="#/search?q=besi+beton">Besi beton</a><a href="#/search?q=semen">Semen</a><a href="#/search?q=cat">Cat</a><a href="#/search?q=pipa">Pipa PVC</a><a href="#/search?q=truck">Truck</a></div></div></article>`).join('')}</div><button class="hero-arrow hero-prev" aria-label="Sebelumnya">‹</button><button class="hero-arrow hero-next" aria-label="Berikutnya">›</button><div class="hero-dots">${slides.map((_,i)=>`<button class="${i===0?'is-active':''}" aria-label="Slide ${i+1}"></button>`).join('')}</div></section>
<main>
<section class="section quick-trust"><div class="section-container"><div class="trust-grid"><div><b>Bandingkan supplier</b><span>Harga, stok & availability</span></div><div><b>One project checkout</b><span>Beberapa supplier, satu alur</span></div><div><b>Coordinated delivery</b><span>Pickup, loading & delivery</span></div><div><b>Track every step</b><span>Dari order sampai proyek</span></div></div></div></section>
<section class="section"><div class="section-container"><div class="section-heading"><div><span class="section-kicker">EXPLORE</span><h2>What do you need for your project?</h2></div><a href="#/material" class="view-all">Lihat semua ${icon.arrow}</a></div><div class="category-scroller">${categories.map(c=>`<a href="#/material/${c[1]}" class="k-category"><div><img src="${c[2]}" alt="${c[0]}" loading="lazy"></div><strong>${c[0]}</strong><small>Explore products</small></a>`).join('')}</div></div></section>
<section class="section soft-section"><div class="section-container"><div class="section-heading"><div><span class="section-kicker">DEALS</span><h2>Popular materials for your project</h2></div><a href="#/material" class="view-all">Lihat semua ${icon.arrow}</a></div><div class="deal-grid">${PRODUCTS.slice(0,6).map(deal).join('')}</div></div></section>
<section class="section"><div class="section-container"><div class="section-heading"><div><span class="section-kicker">SHOP BY AREA</span><h2>Popular project areas</h2></div><a href="#/material" class="view-all">Explore ${icon.arrow}</a></div><div class="destination-grid">${areas.map(a=>`<a href="#/material" class="destination-card"><img src="${a[2]}" alt="${a[0]}" loading="lazy"><div><strong>${a[0]}</strong><span>${a[1]}</span><small>Explore materials ${icon.arrow}</small></div></a>`).join('')}</div></div></section>
<section class="section how-section"><div class="section-container"><div class="section-heading"><div><span class="section-kicker">HOW IT WORKS</span><h2>From search to delivery</h2></div><a href="#/help" class="view-all">Pelajari ${icon.arrow}</a></div><div class="how-grid"><div><b>01</b><h3>Search</h3><p>Temukan material, supplier dan opsi delivery.</p></div><div><b>02</b><h3>Compare</h3><p>Bandingkan harga, stok, rating dan availability.</p></div><div><b>03</b><h3>Order</h3><p>Gabungkan material dari beberapa supplier.</p></div><div><b>04</b><h3>Deliver</h3><p>Bali Bagus mengoordinasikan pickup sampai proyek.</p></div></div></div></section>
<section class="section soft-section"><div class="section-container"><div class="section-heading"><div><span class="section-kicker">GUIDES</span><h2>Plan your project with confidence</h2></div><a href="#/blog" class="view-all">Baca semua ${icon.arrow}</a></div><div class="guide-grid">${guides.map(g=>`<a href="#/article/${g[0]}" class="guide-card"><img src="${g[3]}" alt="${g[2]}" loading="lazy"><div><small>${g[1]}</small><h3>${g[2]}</h3><span>Read guide ${icon.arrow}</span></div></a>`).join('')}</div></div></section>
<section class="section why-section"><div class="section-container"><div class="why-layout"><div><span class="section-kicker">WHY BALI BAGUS</span><h2>A marketplace built around the way construction actually works.</h2><p>Bukan sekadar katalog. Bali Bagus menyatukan pencarian material, perbandingan supplier, procurement multi-supplier dan delivery dalam satu workflow.</p><a href="#/proyek" class="primary-button">Explore projects ${icon.arrow}</a></div><div class="why-list"><div>${icon.check}<span><b>Multiple supplier offers</b><small>Bandingkan price, stock dan availability.</small></span></div><div>${icon.check}<span><b>Multi-supplier procurement</b><small>Material berbeda, satu checkout.</small></span></div><div>${icon.check}<span><b>Delivery network</b><small>Pickup, loading dan delivery terkoordinasi.</small></span></div><div>${icon.check}<span><b>Reviews & support</b><small>Feedback membantu keputusan pembelian.</small></span></div></div></div></div></section>
</main>${footer()}${nav()}`;
}
export function bindHome(){
 const hero=document.querySelector('.klook-hero');if(hero&&!hero.dataset.ready){hero.dataset.ready='1';const slides=[...hero.querySelectorAll('.hero-slide')],dots=[...hero.querySelectorAll('.hero-dots button')];let n=0,t;const show=i=>{n=(i+slides.length)%slides.length;slides.forEach((s,j)=>s.classList.toggle('is-active',j===n));dots.forEach((d,j)=>d.classList.toggle('is-active',j===n))};const restart=()=>{clearInterval(t);t=setInterval(()=>show(n+1),5500)};hero.querySelector('.hero-prev').onclick=()=>{show(n-1);restart()};hero.querySelector('.hero-next').onclick=()=>{show(n+1);restart()};dots.forEach((d,i)=>d.onclick=()=>{show(i);restart()});restart()}
 document.querySelectorAll('.hero-slide-search').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const q=f.querySelector('input')?.value.trim();if(q)location.hash='#/search?q='+encodeURIComponent(q)}));
 document.querySelectorAll('[data-wish]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const x=PRODUCTS.find(p=>p.id===b.dataset.wish);if(x){store.toggleWishlist(x);b.classList.toggle('is-saved',store.isWishlisted(x.id))}}));
}
