import {PRODUCTS,ALL_CATALOG} from '../data/catalog.js';
import {shell,hero,card,bind,icon} from './ui.js';
import {store,money} from './store.js';
const categories=['Besi & Baja','Semen & Beton','Pasir & Batu','Bata & Blok','Kayu & Plywood','Plumbing','Electrical','Paint','Tools'];
const suppliers=['Mitra Bangunan Bali','Bali Material Center','Supplier Proyek Nusantara'];
const sets={material:PRODUCTS,service:[],logistics:[],property:[]};
function filterPanel(type){return `<aside class="market-filters"><b>Filter results</b><label>Price<input type="range" min="0" max="1000000"></label><label>Supplier<select><option>All suppliers</option>${suppliers.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Rating<select><option>Any rating</option><option>4★ & up</option><option>4.5★ & up</option></select></label><label>Availability<select><option>All</option><option>In stock</option><option>Same-day</option></select></label><label class="check"><input type="checkbox"> Same-day delivery</label><label class="check"><input type="checkbox"> Available nearby</label></aside>`}
function marketCard(x){return `<article class="market-card"><a href="#/detail/${x.id}" class="market-image"><img src="${x.image}" alt="${x.title}" loading="lazy"><button class="save" data-wish="${x.id}">♡</button></a><div class="market-body"><small>Construction material</small><a href="#/detail/${x.id}" class="market-title">${x.title}</a><div class="rating">★ ${x.rating||4.8} <span>(${Math.floor(70+Math.random()*90)})</span></div><strong>Rp ${money(x.price)}</strong><span>/ ${x.unit||'item'}</span><div class="supplier-count">3 suppliers available · Delivery available</div></div></article>`}
export function listing(type,slug=''){let items=(sets[type]||ALL_CATALOG).filter(x=>!slug||x.category===slug);if(type==='material'&&!items.length)items=PRODUCTS;const name=slug?slug.replaceAll('-',' '):type==='material'?'Construction materials':type;const html=shell(`<div class="market-wrap"><div class="breadcrumb">Home / ${name}</div>${hero(type.toUpperCase(),`Shop ${name}`,'Compare supplier offers, stock and delivery options before you buy.')}<div class="listing-top"><div><h2>${items.length} results</h2><p>Prices and availability are demo data until the backend is connected.</p></div><select id="sort"><option>Recommended</option><option>Lowest price</option><option>Highest rated</option><option>Most available</option></select></div><div class="listing-layout">${filterPanel(type)}<div class="catalog-grid market-grid">${items.map(marketCard).join('')}</div></div></div>`,`Shop ${name}`);queueMicrotask(bind);return html}
export function search(q=''){const s=q.toLowerCase();const items=ALL_CATALOG.filter(x=>!s||`${x.title} ${x.provider} ${x.category}`.toLowerCase().includes(s));const html=shell(`<div class="market-wrap"><form id="search-form" class="large-search">${icon.search}<input value="${q}" placeholder="Search materials, products or brands"><button>Search</button></form><div class="breadcrumb">Home / Search</div><div class="listing-top"><div><h1>Search results${q?` for “${q}”`:''}</h1><p>${items.length} products and services found.</p></div><select><option>Recommended</option><option>Lowest price</option><option>Highest rated</option></select></div><div class="listing-layout"><aside class="market-filters"><b>Refine</b><label>Category<select><option>All categories</option>${categories.map(x=>`<option>${x}</option>`).join('')}</select></label><label class="check"><input type="checkbox"> In stock</label><label class="check"><input type="checkbox"> Delivery available</label></aside><div class="catalog-grid market-grid">${items.map(marketCard).join('')||'<div class="empty-state"><h2>No matches found</h2><p>Try a material name, brand or category.</p></div>'}</div></div></div>`,'Search');queueMicrotask(()=>{bind();document.querySelector('#search-form')?.addEventListener('submit',e=>{e.preventDefault();location.hash='#/search?q='+encodeURIComponent(e.target.querySelector('input').value)})});return html}