import {PRODUCTS,SERVICES,LOGISTICS,PROPERTIES,ALL_CATALOG} from '../data/catalog.js';
import {shell,hero,card,bind,icon} from './ui.js';
import {store,money} from './store.js';
import {SUPPLIERS} from '../data/marketplace.js';
import {searchService} from './services.js';

const sets={material:PRODUCTS,service:SERVICES,logistics:LOGISTICS,property:PROPERTIES};
const labels={material:'Materials',service:'Services',logistics:'Delivery & Logistics',property:'Property'};
const categories={material:['besi-baja','semen-beton','pasir-batu','kayu-multiplek','cat-pelapis','pipa-plumbing','listrik','atap'],service:['tukang-bangunan','listrik','plumbing','renovasi'],logistics:['pickup','l300','truck','bongkar-muat'],property:['rumah','tanah','ruko','villa']};
const deliveryAreas={denpasar:'Denpasar',badung:'Badung',ubud:'Ubud',canggu:'Canggu',kuta:'Kuta',gianyar:'Gianyar',tabanan:'Tabanan'};

function marketCard(x){return `<article class="market-card"><a href="#/detail/${x.id}" class="market-image"><img src="${x.image}" alt="${x.title}" loading="lazy"><button type="button" class="save" data-wish="${x.id}" aria-label="Simpan ke wishlist">♡</button></a><div class="market-body"><small>${x.type==='material'?'MATERIAL':x.type.toUpperCase()}</small><a href="#/detail/${x.id}" class="market-title">${x.title}</a><div class="rating">★ ${x.rating||4.8} <span>(demo)</span></div><strong>Rp ${money(x.price)}</strong><span>/ ${x.unit||'item'}</span><div class="supplier-count">${x.type==='material'?'3 supplier · stok & delivery ditampilkan di detail':'Available to book'}</div><a class="market-card-cta" href="#/detail/${x.id}">${x.type==='material'?'Lihat pilihan supplier':'Lihat detail'} →</a></div></article>`}
function filterPanel(type,slug){return `<aside class="market-filters"><b>Filter ${labels[type]}</b><label>Category<select id="filter-category"><option value="">All categories</option>${(categories[type]||[]).map(x=>`<option value="${x}" ${slug===x?'selected':''}>${x.replaceAll('-',' ')}</option>`).join('')}</select></label><label>Supplier<select id="filter-supplier"><option value="">All suppliers</option>${SUPPLIERS.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select></label><label>Rating<select id="filter-rating"><option value="0">Any rating</option><option value="4">4★ & up</option><option value="4.5">4.5★ & up</option></select></label><label>Availability<select><option>All</option><option>In stock</option><option>Same-day</option></select></label><label class="check"><input type="checkbox"> Same-day delivery</label><label class="check"><input type="checkbox"> Available nearby</label></aside>`}
export function listing(type,slug=''){
 let items=[...(sets[type]||[])];
 const area=type==='logistics'?deliveryAreas[slug]:null;
 if(slug&&!area)items=items.filter(x=>x.category===slug);
 if(!items.length&&slug&&!area)items=(sets[type]||[]);
 const name=slug?slug.replaceAll('-',' '):labels[type]||type;
 const displayName=area?area+' Delivery':name;
 const html=shell(`<div class="market-wrap shopee-category-page"><div class="breadcrumb">Home / ${labels[type]||type}${slug?' / '+displayName:''}</div><div class="category-intro"><span class="section-kicker">${type==='material'?'MATERIAL MARKETPLACE':labels[type].toUpperCase()}</span><h1>${slug?displayName.replace(/\b\w/g,m=>m.toUpperCase()):`Shop ${name}`}</h1><p>${area?`Layanan delivery untuk proyek di ${area}. Pilih material, supplier, dan opsi pengiriman sesuai kebutuhan proyek.`:type==='material'?'Bandingkan harga, supplier, stok dan pilihan delivery seperti marketplace—semua dalam satu alur procurement.':'Bandingkan pilihan yang tersedia untuk kebutuhan proyek Anda.'}</p></div><div class="category-tabs"><a class="active" href="#/${typeRoute(type)}${slug?'/'+slug:''}">Semua</a>${(categories[type]||[]).slice(0,7).map(c=>`<a href="#/${typeRoute(type)}/${c}">${c.replaceAll('-',' ')}</a>`).join('')}</div><div class="listing-top"><div><h2><span id="result-count">${items.length}</span> results</h2><p>Prices, stock and ratings are demo data until the backend is connected.</p></div><select id="sort"><option value="recommended">Recommended</option><option value="price_asc">Lowest price</option><option value="price_desc">Highest price</option><option value="rating">Highest rated</option></select></div><div class="listing-layout">${filterPanel(type,slug)}<div class="catalog-grid market-grid" id="market-results">${items.map(marketCard).join('')||'<div class="empty-state"><h2>No matches found</h2></div>'}</div></div></div>`,`Shop ${name}`);
 queueMicrotask(()=>{bind();const grid=document.querySelector('#market-results'),sort=document.querySelector('#sort');sort?.addEventListener('change',()=>{const a=[...(sets[type]||[])].filter(x=>!slug||x.category===slug);const v=sort.value;a.sort((x,y)=>v==='price_asc'?x.price-y.price:v==='price_desc'?y.price-x.price:v==='rating'?(y.rating||0)-(x.rating||0):0);grid.innerHTML=a.map(marketCard).join('');bind()});document.querySelector('#filter-category')?.addEventListener('change',e=>{if(e.target.value)location.hash='#/'+typeRoute(type)+'/'+e.target.value});});
 return html;
}
const typeRoute=t=>t==='service'?'jasa':t==='logistics'?'logistik':t==='property'?'properti':'material';
export function search(q=''){
 const result=searchService.search(q);
 const suggestions=searchService.suggest(q);
 const displayQuery=result.changed?result.corrected:q;
 const html=shell('<div class="market-wrap search-market"><form id="search-form" class="large-search">'+icon.search+'<input value="'+q.replaceAll('"','&quot;')+'" placeholder="Cari material, merek, ukuran atau jasa"><button>Cari</button></form><div class="search-helper">'+(result.changed?'<b>Menampilkan hasil untuk “'+result.corrected+'”</b> · <a href="#/search?q='+encodeURIComponent(q)+'">Cari tetap untuk “'+q+'”</a>':'Ketik kebutuhan seperti semen 50kg, besi 10mm, cat putih atau pipa PVC.')+'</div><div class="breadcrumb">Home / Search</div><div class="search-suggestions"><span>Populer</span>'+suggestions.suggestions.map(x=>'<a href="#/search?q='+encodeURIComponent(x)+'">'+x+'</a>').join('')+'</div><div class="listing-top"><div><h1>Hasil pencarian'+(displayQuery?' untuk “'+displayQuery+'”':'')+'</h1><p>'+result.items.length+' pilihan ditemukan · supplier lintas Bali dapat muncul berdasarkan harga, stok dan delivery.</p></div><select id="search-sort"><option value="relevance">Paling relevan</option><option value="price_asc">Harga terendah</option><option value="price_desc">Harga tertinggi</option><option value="rating">Rating tertinggi</option></select></div><div class="listing-layout"><aside class="market-filters"><b>Filter</b><label>Type<select id="search-type"><option value="">Semua</option><option value="material">Material</option><option value="service">Jasa</option><option value="logistics">Delivery</option></select></label><label class="check"><input id="search-stock" type="checkbox"> Stok tersedia</label><label class="check"><input id="search-today" type="checkbox"> Bisa dikirim hari ini</label><label>Lokasi<select id="search-area"><option value="">Semua Bali</option><option>Denpasar</option><option>Badung</option><option>Gianyar</option><option>Tabanan</option></select></label></aside><div class="catalog-grid market-grid" id="search-results">'+(result.items.map(marketCard).join('')||'<div class="empty-state"><h2>Material belum ditemukan</h2><p>Coba nama material, merek, ukuran, atau kategori lain.</p><a class="primary-button" href="#/material">Jelajahi kategori</a></div>')+'</div></div></div>','Search');
 queueMicrotask(()=>{bind();const renderSearch=()=>{const opts={sort:document.querySelector('#search-sort')?.value||'relevance',type:document.querySelector('#search-type')?.value||''};let a=searchService.search(q,opts).items;if(document.querySelector('#search-stock')?.checked)a=a.filter(x=>Number(x.stock||0)>0);if(document.querySelector('#search-today')?.checked)a=a.filter(x=>String(x.availability||'').toLowerCase().includes('same-day'));const area=document.querySelector('#search-area')?.value;if(area)a=a.filter(x=>String(x.area||x.location||x.provider||'').toLowerCase().includes(area.toLowerCase())||String(x.availability||'').toLowerCase().includes('available'));document.querySelector('#search-results').innerHTML=a.map(marketCard).join('')||'<div class="empty-state"><h2>Tidak ada hasil yang cocok</h2><p>Ubah filter atau coba nama material yang lebih umum.</p></div>';bind()};document.querySelector('#search-form')?.addEventListener('submit',e=>{e.preventDefault();const v=e.target.querySelector('input').value.trim();location.hash='#/search?q='+encodeURIComponent(v)});document.querySelector('#search-sort')?.addEventListener('change',renderSearch);document.querySelector('#search-type')?.addEventListener('change',renderSearch);document.querySelector('#search-stock')?.addEventListener('change',renderSearch);document.querySelector('#search-today')?.addEventListener('change',renderSearch);document.querySelector('#search-area')?.addEventListener('change',renderSearch);});
 return html;
}
