import {listing,search} from './page-factory.js';
import {categoryPage} from '../pages/category/index.js';
import {detail} from '../pages/product/detail.js';
import {cart} from '../pages/cart/index.js';
import {checkout} from '../pages/checkout/index.js';
import {orders,order} from '../pages/orders/index.js';
import {wishlist} from '../pages/wishlist/index.js';
import {login} from '../pages/auth/index.js';
import {misc} from '../pages/misc/index.js';
import {blog} from '../pages/blog/index.js';
import {supplierPage} from '../pages/provider/index.js';
import {projectsPage} from '../pages/project/index.js';
import {home} from '../pages/home/index.js';
import {operations} from '../pages/operations/index.js';
import {tracking} from '../pages/tracking/index.js';
import {updateSEO} from '../pages/seo.js';

export function route(homeFn=home){
 const raw=(location.hash||'#/').replace(/^#\/?/,'');
 const [path,q='']=raw.split('?');
 const s=path.split('/').filter(Boolean),r=s[0],v=s[1],p=new URLSearchParams(q);
 let h;
 if(!r)h=homeFn();
 else if(r==='search')h=search(p.get('q')||'');
 else if(r==='material'||r==='materials')h=v?categoryPage(v):listing('material','');
 else if(r==='jasa')h=v?categoryPage(v==='plumbing'?'plumbing-service':v):listing('service','');
 else if(r==='logistik'||r==='delivery')h=v?categoryPage(v):listing('logistics','');
 else if(r==='properti')h=listing('property',v||'');
 else if(r==='detail'||r==='product')h=detail(v);
 else if(r==='cart')h=cart();
 else if(r==='checkout')h=checkout();
 else if(r==='orders')h=orders();
 else if(r==='order')h=order(v);
 else if(r==='wishlist')h=wishlist();
 else if(r==='login'||r==='register')h=login();
 else if(r==='blog'||r==='guides'||r==='article')h=blog(r==='article'||r==='guides'?v:'');
 else if(r==='provider'||r==='suppliers')h=supplierPage(v||'');
 else if(r==='proyek'||r==='projects')h=projectsPage(v||'');
 else if(['promo','help','faq','about','contact','reviews','terms','privacy','recent'].includes(r))h=misc(r);
 else if(['account','seller','driver','partner','admin'].includes(r))h=operations(r,v||'');
 else if(r==='track'||r==='track-order')h=tracking(v||p.get('id')||'');
 else h='<div class="empty-state large"><h1>Halaman tidak ditemukan</h1><p>Rute belum tersedia pada frontend ini.</p><a class="primary-button" href="#/">Kembali ke beranda</a></div>';
 document.querySelector('#app').innerHTML=h;
 updateSEO({title:document.querySelector('h1')?.textContent?document.querySelector('h1').textContent+' — Bali Bagus':'Bali Bagus Load & Delivery',description:'Material konstruksi, supplier, procurement dan delivery untuk kebutuhan proyek.',path:path});
 window.scrollTo(0,0);
}
