import {store,money} from './store.js';
export const icon={location:`<svg viewBox="0 0 24 24"><path d="M12 21s7-6.2 7-12a7 7 0 1 0-14 0c0 5.8 7 12 7 12Z"/><circle cx="12" cy="9" r="2.2"/></svg>`,truck:`<svg viewBox="0 0 24 24"><path d="M3 6h11v10H3zM14 10h4l3 3v3h-7z"/><circle cx="7" cy="18" r="1.8"/><circle cx="18" cy="18" r="1.8"/></svg>`,store:`<svg viewBox="0 0 24 24"><path d="M4 10h16v10H4zM3 10l2-6h14l2 6M8 20v-6h8v6"/></svg>`,box:`<svg viewBox="0 0 24 24"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></svg>`,menu:`<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg>`,search:`<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.5 4.5"/></svg>`,cart:`<svg viewBox="0 0 24 24"><path d="M3 4h2l2.1 10.1a2 2 0 0 0 2 1.6h7.8a2 2 0 0 0 1.9-1.4L21 8H6"/><circle cx="10" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></svg>`,heart:`<svg viewBox="0 0 24 24"><path d="M20.8 8.8c0 5.1-8.8 10.3-8.8 10.3S3.2 13.9 3.2 8.8A4.8 4.8 0 0 1 8 4c1.7 0 3.2.9 4 2.2C12.8 4.9 14.3 4 16 4a4.8 4.8 0 0 1 4.8 4.8Z"/></svg>`,back:`<svg viewBox="0 0 24 24"><path d="M19 12H5"/><path d="m11 6-6 6 6 6"/></svg>`,arrow:`<svg viewBox="0 0 24 24"><path d="M5 12h13"/><path d="m13 6 6 6-6 6"/></svg>`,user:`<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.5"/><path d="M5 20c.8-3.3 3.2-5 7-5s6.2 1.7 7 5"/></svg>`,check:`<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>`};
const mega=[['besi-baja','Besi & Baja',['Besi Beton','Besi Ulir','Wiremesh','Baja Ringan']],['semen-beton','Semen & Beton',['Semen Portland','Mortar','Beton']],['pasir-batu','Pasir & Batu',['Pasir','Batu Split','Batu Kali']],['listrik','Listrik',['Kabel','Saklar','Panel Listrik']],['pipa-plumbing','Plumbing',['Pipa PVC','Fitting','Valve']]];
function megaMenu(slug,title,items){return `<div class="category-mega"><div class="category-mega-inner"><div class="mega-feature"><span class="mega-kicker">BALI BAGUS</span><h3>${title}</h3><p>Bandingkan produk, supplier, stok dan pilihan delivery untuk proyek Anda.</p><a href="#/material/${slug}" class="mega-all">Lihat semua ${icon.arrow}</a></div><div class="mega-column"><strong>Pilihan material</strong>${items.map((x,i)=>`<a href="#/search?q=${encodeURIComponent(x)}"><span class="mega-icon">${['▦','◈','◇','◉'][i%4]}</span>${x}</a>`).join('')}</div><div class="mega-column"><strong>Jelajahi</strong><a href="#/material/${slug}"><span class="mega-icon">⌕</span>Semua produk</a><a href="#/provider"><span class="mega-icon">♙</span>Supplier terverifikasi</a><a href="#/logistik"><span class="mega-icon">▱</span>Delivery proyek</a></div><div class="mega-column mega-project"><strong>Butuh bantuan?</strong><a href="#/proyek"><span class="mega-icon">⌂</span>Rekomendasi proyek</a><a href="#/help"><span class="mega-icon">?</span>Pusat bantuan</a></div></div></div>`}
export function header(title='Bali Bagus'){
 const user=store.getUser();
 const account=user?'<a href="#/account" class="header-account">'+icon.user+'<span>'+String(user.name||'Akun')+'</span></a><a href="#/" class="header-logout" data-logout>Logout</a><a href="#/account" class="header-mobile-account" aria-label="Akun">'+icon.user+'</a>':'<a href="#/register" class="header-register">Mendaftar</a><a href="#/login" class="header-login">Login</a><a href="#/login" class="header-mobile-account" aria-label="Akun">'+icon.user+'</a>';
 const cat=(slug,label)=>'<a href="#/material/'+slug+'">'+label+'</a>';
 return '<header class="site-header app-market-header sticky-header"><div class="topbar"><div class="header-inner"><button class="mobile-menu-button" aria-label="Menu">'+icon.menu+'</button><a class="brand" href="#/"><span class="brand-mark">B</span><span class="brand-copy"><strong>BALI BAGUS</strong><small>LOAD & DELIVERY</small></span></a><form class="header-search" id="header-search-form"><span>${icon.search}</span><input name="q" placeholder="Cari material, supplier, atau layanan" aria-label="Cari material, supplier, atau layanan"><button type="submit">Cari</button></form><nav class="primary-links"><div class="header-locale"><a href="#/blog">ID</a><span>|</span><a href="#/blog">IDR</a></div><a href="#/blog">Blog</a><a href="#/help">Bantuan</a><a href="#/wishlist">'+icon.heart+'<span>Wishlist</span></a><a href="#/recent">Baru dilihat</a>'+account+'<a href="#/cart" class="cart-action">'+icon.cart+'<i>'+store.cartCount()+'</i></a></nav></div></div><nav class="category-nav"><div class="category-nav-inner">'+cat('besi-baja','Besi & Baja')+cat('semen-beton','Semen & Beton')+cat('pasir-batu','Pasir & Batu')+cat('kayu-multiplek','Kayu & Multiplek')+cat('cat-pelapis','Cat & Finishing')+cat('listrik','Listrik')+cat('pipa-plumbing','Plumbing')+cat('atap','Atap')+'<a href="#/jasa">Jasa</a><a href="#/logistik">Angkutan & Delivery</a></div></nav></header>';
}
export function shell(content,title='Bali Bagus',options={}){
 const pageTitle=String(title||'Bali Bagus').replace(/\\s+—\\s+Bali Bagus.*$/,'');
 const titleLower=pageTitle.toLowerCase();
 const heroImage=titleLower.includes('supplier')?'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=2200&q=88':titleLower.includes('delivery')||titleLower.includes('logistik')?'https://images.unsplash.com/photo-1601584115197-04ecc0da31d8?auto=format&fit=crop&w=2200&q=88':titleLower.includes('jasa')?'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=2200&q=88':'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=2200&q=88';
 const heroDescription=options.heroDescription||(titleLower.includes('supplier')?'Temukan supplier material, bandingkan pilihan, dan kelola kebutuhan pengadaan proyek dalam satu alur.':titleLower.includes('delivery')||titleLower.includes('logistik')?'Atur pengiriman material proyek dengan pilihan layanan dan koordinasi yang lebih praktis.':titleLower.includes('wishlist')||titleLower.includes('dilihat')?'Simpan dan tinjau kembali material yang Anda pertimbangkan untuk kebutuhan proyek.':titleLower.includes('pesanan')||titleLower.includes('order')||titleLower.includes('track')?'Pantau detail pesanan dan tahapan pengadaan material proyek Anda.':'Temukan material, bandingkan supplier, atur delivery, dan kelola kebutuhan proyek dari satu marketplace.');
 const noHeroTitles=['cart','checkout','booking','book appointment','pesanan','status pesanan','track order','tracking','masuk','login','register','akun','account','payment','pembayaran','form pemesanan','buat pesanan','wishlist','baru dilihat','recent','bantuan','help','faq','kontak','contact','ulasan','reviews','syarat','terms','privasi','privacy','operations','console','seller center','driver center','fleet partner'];
 const noHero=options.hero===false||options.hero==='none'||noHeroTitles.some(x=>titleLower===x||titleLower.startsWith(x+' ')||titleLower.startsWith(x+' —'));
 const hero=noHero?'':`<section class="klook-hero hero-carousel global-page-hero"><div class="hero-slides"><article class="hero-slide is-active" style="--hero-image:url('${heroImage}')"><div class="klook-hero-overlay"></div><div class="klook-hero-inner"><span class="hero-label">${options.heroLabel||'BALI BAGUS LOAD & DELIVERY'}</span><div class="hero-location">Untuk kebutuhan proyek di Bali & Indonesia</div><h1>${pageTitle}</h1><p>${heroDescription}</p></div></article></div></section>`; return `${header(title)}${hero}<main class="page-main">${content}</main>${footer()}${nav()}`;
}
export function nav(){const user=store.getUser();return `<nav class="mobile-bottom-nav app-nav"><a href="#/"><span>⌂</span><small>Home</small></a><a href="#/material"><span>▦</span><small>Produk</small></a><a href="#/orders"><span>✓</span><small>Pesanan</small></a><a href="#/cart"><span>🛒</span><small>Cart</small></a><a href="${user?'#/orders':'#/login'}"><span>○</span><small>Akun</small></a></nav>`}
export function pageHeading(k,t,p='',action=''){return `<section class="page-heading"><div class="page-heading-copy"><span class="eyebrow">${k}</span><h1>${t}</h1>${p?`<p>${p}</p>`:''}</div>${action}</section>`}
export function hero(k,t,p=''){return `<section class="page-hero"><span class="eyebrow">${k}</span><h1>${t}</h1><p>${p}</p></section>`}
export function card(x){return `<article class="catalog-card"><a class="catalog-image" href="#/detail/${x.id}"><img src="${x.image}" alt="${x.title}" loading="lazy"></a><div class="catalog-body"><small>${x.type}</small><a class="catalog-title" href="#/detail/${x.id}">${x.title}</a><strong>Rp ${money(x.price)}</strong><span>/ ${x.unit||'item'}</span><div class="catalog-meta">★ ${x.rating||4.8} · ${x.stock||'Available'}</div><small>${x.provider||'Bali Bagus supplier network'}</small></div></article>`}
export function bind(){document.querySelector('#header-search-form')?.addEventListener('submit',e=>{e.preventDefault();const q=e.currentTarget.querySelector('input')?.value.trim();if(q)location.hash='#/search?q='+encodeURIComponent(q)});document.querySelectorAll('[data-wish]').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const x=window.__BLD_GET_ITEM?.(b.dataset.wish);if(x){store.toggleWishlist(x);b.textContent=store.isWishlisted(x.id)?'♥':'♡'}});document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>history.back());document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=e=>{e.preventDefault();store.clearUser();location.hash='#/';location.reload()})}
export function toast(t){const x=document.createElement('div');x.className='bld-toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),1800)}
export function footer(){return `<footer class="site-footer"><div class="footer-main"><div class="footer-container"><div class="footer-brand"><a href="#/" class="brand footer-logo"><span class="brand-mark">B</span><span class="brand-copy"><strong>BALI BAGUS</strong><small>LOAD & DELIVERY</small></span></a><p>Marketplace kebutuhan proyek untuk material, procurement dan delivery.</p><div class="footer-social"><a href="#" aria-label="Instagram">IG</a><a href="#" aria-label="Facebook">FB</a><a href="#" aria-label="YouTube">YT</a><a href="#" aria-label="TikTok">TK</a></div></div><div class="footer-column"><h3>Belanja</h3><a href="#/material">Material</a><a href="#/material/besi-baja">Besi & Baja</a><a href="#/material/semen-beton">Semen & Beton</a><a href="#/material/pasir-batu">Pasir & Batu</a><a href="#/promo">Promo</a></div><div class="footer-column"><h3>Jasa</h3><a href="#/jasa">Semua Jasa</a><a href="#/jasa/tukang-bangunan">Tukang</a><a href="#/jasa/listrik">Listrik</a><a href="#/jasa/plumbing">Plumbing</a><a href="#/jasa/renovasi">Renovasi</a></div><div class="footer-column"><h3>Logistik</h3><a href="#/logistik">Semua Logistik</a><a href="#/logistik/pickup">Pickup</a><a href="#/logistik/l300">L300</a><a href="#/logistik/truck">Truck</a><a href="#/logistik/bongkar-muat">Bongkar Muat</a></div><div class="footer-column"><h3>Belanja</h3><a href="#/wishlist">Wishlist</a><a href="#/orders">Pesanan</a><a href="#/proyek">Projects</a><a href="#/provider">Suppliers</a><a href="#/blog">Guides</a></div><div class="footer-column"><h3>Bantuan</h3><a href="#/help">Pusat Bantuan</a><a href="#/faq">FAQ</a><a href="#/contact">Hubungi Kami</a><a href="#/provider">Untuk Supplier</a><a href="#/reviews">Ulasan</a></div></div></div><div class="footer-bottom"><div class="footer-container footer-bottom-inner"><div><strong>© 2026 Bali Bagus Load & Delivery</strong><span>Platform kebutuhan proyek Indonesia</span></div><div class="footer-bottom-links"><a href="#/terms">Syarat & Ketentuan</a><a href="#/privacy">Kebijakan Privasi</a><a href="#/help">Bantuan</a></div></div></div></footer>`}